language: php

php:
  - 5.5
  - 5.6
  - 7.1
  - 7.2
  - 7.3
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --debug tests/